// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: writeshard/write_shard.proto

package writeshard

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WriteShard_ExecuteBlock_FullMethodName = "/writeshard.WriteShard/ExecuteBlock"
)

// WriteShardClient is the client API for WriteShard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WriteShardClient interface {
	ExecuteBlock(ctx context.Context, in *ExecuteBlockRequest, opts ...grpc.CallOption) (*ExecuteBlockResponse, error)
}

type writeShardClient struct {
	cc grpc.ClientConnInterface
}

func NewWriteShardClient(cc grpc.ClientConnInterface) WriteShardClient {
	return &writeShardClient{cc}
}

func (c *writeShardClient) ExecuteBlock(ctx context.Context, in *ExecuteBlockRequest, opts ...grpc.CallOption) (*ExecuteBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteBlockResponse)
	err := c.cc.Invoke(ctx, WriteShard_ExecuteBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WriteShardServer is the server API for WriteShard service.
// All implementations must embed UnimplementedWriteShardServer
// for forward compatibility.
type WriteShardServer interface {
	ExecuteBlock(context.Context, *ExecuteBlockRequest) (*ExecuteBlockResponse, error)
	mustEmbedUnimplementedWriteShardServer()
}

// UnimplementedWriteShardServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWriteShardServer struct{}

func (UnimplementedWriteShardServer) ExecuteBlock(context.Context, *ExecuteBlockRequest) (*ExecuteBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteBlock not implemented")
}
func (UnimplementedWriteShardServer) mustEmbedUnimplementedWriteShardServer() {}
func (UnimplementedWriteShardServer) testEmbeddedByValue()                    {}

// UnsafeWriteShardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WriteShardServer will
// result in compilation errors.
type UnsafeWriteShardServer interface {
	mustEmbedUnimplementedWriteShardServer()
}

func RegisterWriteShardServer(s grpc.ServiceRegistrar, srv WriteShardServer) {
	// If the following call pancis, it indicates UnimplementedWriteShardServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WriteShard_ServiceDesc, srv)
}

func _WriteShard_ExecuteBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteShardServer).ExecuteBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteShard_ExecuteBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteShardServer).ExecuteBlock(ctx, req.(*ExecuteBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WriteShard_ServiceDesc is the grpc.ServiceDesc for WriteShard service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WriteShard_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "writeshard.WriteShard",
	HandlerType: (*WriteShardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteBlock",
			Handler:    _WriteShard_ExecuteBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "writeshard/write_shard.proto",
}
