// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: writeshard/write_shard.proto

package writeshard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockBytes    []byte                 `protobuf:"bytes,1,opt,name=block_bytes,json=blockBytes,proto3" json:"block_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteBlockRequest) Reset() {
	*x = ExecuteBlockRequest{}
	mi := &file_writeshard_write_shard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBlockRequest) ProtoMessage() {}

func (x *ExecuteBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_writeshard_write_shard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBlockRequest.ProtoReflect.Descriptor instead.
func (*ExecuteBlockRequest) Descriptor() ([]byte, []int) {
	return file_writeshard_write_shard_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteBlockRequest) GetBlockBytes() []byte {
	if x != nil {
		return x.BlockBytes
	}
	return nil
}

type ExecuteBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteBlockResponse) Reset() {
	*x = ExecuteBlockResponse{}
	mi := &file_writeshard_write_shard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBlockResponse) ProtoMessage() {}

func (x *ExecuteBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_writeshard_write_shard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBlockResponse.ProtoReflect.Descriptor instead.
func (*ExecuteBlockResponse) Descriptor() ([]byte, []int) {
	return file_writeshard_write_shard_proto_rawDescGZIP(), []int{1}
}

var File_writeshard_write_shard_proto protoreflect.FileDescriptor

const file_writeshard_write_shard_proto_rawDesc = "" +
	"\n" +
	"\x1cwriteshard/write_shard.proto\x12\n" +
	"writeshard\"6\n" +
	"\x13ExecuteBlockRequest\x12\x1f\n" +
	"\vblock_bytes\x18\x01 \x01(\fR\n" +
	"blockBytes\"\x16\n" +
	"\x14ExecuteBlockResponse2_\n" +
	"\n" +
	"WriteShard\x12Q\n" +
	"\fExecuteBlock\x12\x1f.writeshard.ExecuteBlockRequest\x1a .writeshard.ExecuteBlockResponseB8Z6github.com/ava-labs/avalanchego/atlas/proto/writeshardb\x06proto3"

var (
	file_writeshard_write_shard_proto_rawDescOnce sync.Once
	file_writeshard_write_shard_proto_rawDescData []byte
)

func file_writeshard_write_shard_proto_rawDescGZIP() []byte {
	file_writeshard_write_shard_proto_rawDescOnce.Do(func() {
		file_writeshard_write_shard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_writeshard_write_shard_proto_rawDesc), len(file_writeshard_write_shard_proto_rawDesc)))
	})
	return file_writeshard_write_shard_proto_rawDescData
}

var file_writeshard_write_shard_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_writeshard_write_shard_proto_goTypes = []any{
	(*ExecuteBlockRequest)(nil),  // 0: writeshard.ExecuteBlockRequest
	(*ExecuteBlockResponse)(nil), // 1: writeshard.ExecuteBlockResponse
}
var file_writeshard_write_shard_proto_depIdxs = []int32{
	0, // 0: writeshard.WriteShard.ExecuteBlock:input_type -> writeshard.ExecuteBlockRequest
	1, // 1: writeshard.WriteShard.ExecuteBlock:output_type -> writeshard.ExecuteBlockResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_writeshard_write_shard_proto_init() }
func file_writeshard_write_shard_proto_init() {
	if File_writeshard_write_shard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_writeshard_write_shard_proto_rawDesc), len(file_writeshard_write_shard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_writeshard_write_shard_proto_goTypes,
		DependencyIndexes: file_writeshard_write_shard_proto_depIdxs,
		MessageInfos:      file_writeshard_write_shard_proto_msgTypes,
	}.Build()
	File_writeshard_write_shard_proto = out.File
	file_writeshard_write_shard_proto_goTypes = nil
	file_writeshard_write_shard_proto_depIdxs = nil
}
